### PR TITLE
Port custom errors to the new parser

### LINKED ISSUE #5773: Rewrite the custom syntax error hints to the new parser
In #5693, I've removed custom few error hints created using the parser I've removed. This lead to a few error message quality degradations. They are marked with `# XXX: error recovery quality regression'.

They have to be fixed.

### PR DESCRIPTION
**Pull request by aljazerzen**
Closes #5773

- port custom errors to the new parser
- fix most of the regressions
- hint and details fields
- production names
- a few tweaks
- format and lint

### CODE REVIEW

File: edb/edgeql-parser/src/parser.rs [hunk 1]
```diff
@@ -225,6 +254,7 @@ pub struct Terminal {
 pub struct Production<'a> {
     pub id: usize,
     pub args: &'a [CSTNode<'a>],
+    pub inlined_ids: Option<&'a [usize]>,
```
Comment (msullivan) [inline edb/edgeql-parser/src/parser.rs:257]: Document what that is for? It's because we need to know inlined ids for error processing?

File: edb/edgeql-parser/src/parser.rs [hunk 2]
```diff
@@ -296,12 +332,26 @@ impl<'s> Parser<'s> {
...
             if let Some(inline_position) = ctx.spec.inlines.get(&production.id) {
+                let inlined_id = production.id;
                 // inline rule found
                 let args = production.args;
                 let span = get_span_of_nodes(args);
 
                 value = args[*inline_position as usize];
 
+                // save inlined id
+                if let CSTNode::Production(new_prod) = &mut value {
```
Comment (msullivan) [inline edb/edgeql-parser/src/parser.rs:343]: Do we have any deep inlining chains, since this can be quadratic? (Probably our chains are small enough we don't really care?)

File: edb/edgeql-parser/src/parser/custom_errors.rs [hunk 3]
```diff
@@ -0,0 +1,420 @@
...
+        //     span,
+        //     ..
+        // }) = ltok.value
+        // {
+        //     if kw.is_reserved() {
+        //         // Unexpected reserved keyword:
+        //         // likely an attempt to use keyword as identifier
+        //         return Some(unexpected_reserved_keyword(text, *span));
+        //     }
+        // }
```
Comment (msullivan) [inline edb/edgeql-parser/src/parser/custom_errors.rs:43]: ?

File: edb/edgeql-parser/src/parser/custom_errors.rs [hunk 4]
```diff
@@ -0,0 +1,420 @@
...
+    pub(super) fn custom_error(&self, ctx: &Context, token: &Terminal) -> Option<Error> {
+        // self.print_stack(ctx);
+        let ltok = self.get_from_top(0).unwrap();
+
+        if let Some(value) = self.custom_error_from_rule(token, ctx) {
+            return Some(value);
+        }
+
+        if matches!(token.kind, Kind::Keyword(Keyword("explain"))) {
+            let _hint = "Use `analyze` to show query performance details";
```
Comment (msullivan) [inline edb/edgeql-parser/src/parser/custom_errors.rs:16]: Not used... why?

File: edb/edgeql-parser/src/parser/custom_errors.rs [hunk 5]
```diff
@@ -0,0 +1,420 @@
+use crate::tokenizer::Kind;
+use crate::{keywords::Keyword, position::Span};
+
+use super::{CSTNode, Context, Error, Parser, StackNode, Terminal};
+
+impl<'s> Parser<'s> {
+    pub(super) fn custom_error(&self, ctx: &Context, token: &Terminal) -> Option<Error> {
+        // self.print_stack(ctx);
```
Comment (msullivan) [inline edb/edgeql-parser/src/parser/custom_errors.rs:8]: Stray

File: edb/edgeql-parser/src/parser/custom_errors.rs [hunk 6]
```diff
@@ -0,0 +1,420 @@
...
+                        Cond::keyword("select"),
+                        Cond::keyword("for"),
+                        Cond::keyword("insert"),
+                        Cond::keyword("update"),
+                        Cond::keyword("delete"),
+                    ])
+                    .check(last, ctx)
+            => {
+                return Some(Error {
+                    message: "Missing parenthesis around statement used as an expression"
```
Comment (msullivan) [inline edb/edgeql-parser/src/parser/custom_errors.rs:81]: parentheses

File: edb/edgeql-parser/src/parser/custom_errors.rs [hunk 7]
```diff
@@ -0,0 +1,420 @@
...
+            //         | Kind::Keyword(Keyword("false"))
+            // ) && !Cond::Terminal(Kind::Comma).check(last) =>
+            // {
+            //     // The offending token was something that could
+            //     // make an expression
+            //     return Some(Error::new(format!(
+            //         "It appears that a ',' is missing in {rule} before {}",
+            //         token.text
+            //     )));
+            // }
```
Comment (msullivan) [inline edb/edgeql-parser/src/parser/custom_errors.rs:120]: ?

**Review by msullivan — APPROVED** [review]

File: edb/edgeql-parser/src/parser.rs (hunk 2 above)
Comment (aljazerzen) [reply edb/edgeql-parser/src/parser.rs:343]: I don't know, actually, but I can test it.

File: edb/edgeql-parser/src/parser/custom_errors.rs (hunk 3 above)
Comment (aljazerzen) [reply edb/edgeql-parser/src/parser/custom_errors.rs:43]: These are rules that I've ported from the previous implementation, but are already implemented by the new "Missing x" errors.

I guess we will not need them anymore so they can be removed.

File: edb/edgeql-parser/src/parser.rs (hunk 2 above)
Comment (aljazerzen) [reply edb/edgeql-parser/src/parser.rs:356]: The longest chain found in fast tests is 8. Not critical.
